"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _portfolio_content from './portfolio-content.bones.json'

configureBoneyard({"color":"rgba(0, 255, 136, 0.05)","darkColor":"rgba(0, 255, 136, 0.05)","animate":"shimmer","shimmerColor":"rgba(0, 255, 136, 0.15)","darkShimmerColor":"rgba(0, 255, 136, 0.15)","speed":"2s","shimmerAngle":110})

registerBones({
  "portfolio-content": _portfolio_content,
})
