"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _portfolio_content from './portfolio-content.bones.json'

configureBoneyard({"color":"var(--bg-card)","darkColor":"var(--bg-card)","animate":"shimmer","shimmerColor":"var(--border-color)","darkShimmerColor":"var(--border-color)","speed":"2s","shimmerAngle":110})

registerBones({
  "portfolio-content": _portfolio_content,
})
